name: Build and Upload Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: x86_64-unknown-linux-musl
            target: linux-amd64
            os: ubuntu-latest
            build: zig
            ext: ""

          - toolchain: aarch64-unknown-linux-musl
            target: linux-arm64
            os: ubuntu-latest
            build: zig
            ext: ""

          - toolchain: aarch64-apple-darwin
            target: macos-arm64
            os: macos-latest-arm
            build: raw
            ext: ""

          - toolchain: x86_64-pc-windows-msvc
            target: win-x64
            os: windows-latest
            build: raw
            ext: ".exe"

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode for macOS targets
        if: ${{ matrix.os == 'macos-latest-arm' }}
        run: |
          xcodebuild -version
          xcrun --sdk macosx --show-sdk-path
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV
          echo "DEVELOPER_DIR=$(xcode-select -p)" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.toolchain }}

      - name: Install Zig
        if: ${{ matrix.build == 'zig' }}
        uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-zigbuild
        if: ${{ matrix.build == 'zig' }}
        run: cargo install cargo-zigbuild --locked

      - name: Build Zig
        if: ${{ matrix.build == 'zig' }}
        run: |
          cargo zigbuild \
            --release \
            --target ${{ matrix.toolchain }} \
            --bin cache_cat \
            --bin cache_cat_ping

      - name: Build
        if: ${{ matrix.build == 'raw' }}
        run: cargo build --release --target ${{ matrix.toolchain }} --bin cache_cat --bin cache_cat_ping

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache_cat-${{ matrix.target }}
          path: |
            target/${{ matrix.toolchain }}/release/cache_cat${{ matrix.ext }}
            target/${{ matrix.toolchain }}/release/cache_cat_ping${{ matrix.ext }}

      - name: Rename release file
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          cp "target/${{ matrix.toolchain }}/release/cache_cat${{ matrix.ext }}" \
             "target/${{ matrix.toolchain }}/release/cache_cat-${{ matrix.target }}${{ matrix.ext }}"

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "This is an automated release."
          draft: false
          prerelease: false
          files: |
            target/${{ matrix.toolchain }}/release/cache_cat-${{ matrix.target }}${{ matrix.ext }}

  publish-docker:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/docker-build-publish.yaml